# Generated by Django 4.2.5 on 2024-11-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0005_alter_category_category_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyImage',
        ),
    ]
