# Generated by Django 4.2.5 on 2024-11-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serv', '0006_delete_myimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('accepted', 'принят'), ('reject', 'отклонен'), ('wait', 'ожидает')], default='wait', max_length=10),
        ),
    ]
